/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  "title": "IvorySQL",
  "tagline": "Open Source Oracle compatible PostgreSQL",
  "url": "https://ivorySQL.org",
  "baseUrl": "/",
  "onBrokenLinks": "throw",
  "onBrokenMarkdownLinks": "warn",
  "favicon": "img/favicon.ico",
  "organizationName": "IvorySQL",
  "projectName": "ivory-www",
  "presets": [
    [
      "@docusaurus/preset-classic",
      {
        "docs": {
          "versions": {
            "current": {
              "label": "Devel"
            }
          },
          "sidebarPath": "F:\\docusaurus\\1.9\\11.1\\sidebars.js",
          "editCurrentVersion": false
        },
        "blog": {
          "showReadingTime": true,
          "blogSidebarTitle": "IvorySQL Blogs"
        },
        "theme": {
          "customCss": "F:\\docusaurus\\1.9\\11.1\\src\\css\\custom.css"
        }
      }
    ]
  ],
  "i18n": {
    "defaultLocale": "en",
    "locales": [
      "en",
      "zh-CN"
    ],
    "path": "i18n",
    "localeConfigs": {}
  },
  "themeConfig": {
    "navbar": {
      "style": "dark",
      "title": "IvorySQL",
      "logo": {
        "alt": "IvorySQL Logo",
        "src": "img/ivory.png"
      },
      "items": [
        {
          "label": "Docs",
          "type": "doc",
          "docId": "intro",
          "position": "left"
        },
        {
          "to": "/blog",
          "label": "Blog",
          "position": "left"
        },
        {
          "label": "Downloads",
          "href": "https://github.com/IvorySQL/IvorySQL/releases",
          "position": "left"
        },
        {
          "label": "Releases",
          "to": "/releases-page",
          "position": "left"
        },
        {
          "type": "dropdown",
          "position": "left",
          "label": "Resources",
          "items": [
            {
              "label": "Webinars",
              "to": "/webinars-page"
            },
            {
              "label": "Partners",
              "to": "/partners-page"
            },
            {
              "label": "Customer Stories",
              "href": "customer-stories-page"
            },
            {
              "label": "Contribution Guidelines",
              "to": "/contribution-guidelines"
            }
          ]
        },
        {
          "type": "docsVersionDropdown",
          "position": "right",
          "nextVersionLabel": "Devel",
          "dropdownItemsBefore": [],
          "dropdownItemsAfter": []
        },
        {
          "label": "Community",
          "to": "/community-page",
          "position": "right"
        },
        {
          "href": "https://gitee.com/IvorySQL/",
          "label": "Gitee",
          "position": "right"
        },
        {
          "href": "https://github.com/IvorySQL/IvorySQL",
          "label": "GitHub",
          "position": "right"
        },
        {
          "type": "localeDropdown",
          "position": "right",
          "dropdownItemsBefore": [],
          "dropdownItemsAfter": []
        }
      ],
      "hideOnScroll": false
    },
    "footer": {
      "style": "dark",
      "links": [
        {
          "title": "Docs",
          "items": [
            {
              "label": "Docs",
              "to": "/docs/intro"
            }
          ]
        },
        {
          "title": "Community",
          "items": [
            {
              "label": "Hackers mailing list",
              "href": "https://lists.ivorysql.org/postorius/lists/hackers.ivorysql.org/"
            },
            {
              "label": "Users mailing list",
              "href": "https://lists.ivorysql.org/postorius/lists/general.ivorysql.org/"
            },
            {
              "label": "Mailing Lists",
              "href": "https://lists.IvorySQL.org"
            },
            {
              "label": "Twitter",
              "href": "https://twitter.com/IvorySQL"
            }
          ]
        },
        {
          "title": "More",
          "items": [
            {
              "label": "IvorySQL GitHub",
              "href": "https://github.com/IvorySQL/IvorySQL"
            },
            {
              "label": "IvorySQL Gitee",
              "href": "https://gitee.com/IvorySQL/"
            },
            {
              "label": "IvorySQL YUM",
              "href": "https://yum.highgo.ca/ivorysql.html"
            },
            {
              "label": "Report an issue",
              "href": "https://github.com/IvorySQL/IvorySQL/issues/new/choose"
            }
          ]
        }
      ],
      "copyright": "Copyright © 2023 IvorySQL."
    },
    "colorMode": {
      "defaultMode": "light",
      "disableSwitch": false,
      "respectPrefersColorScheme": false
    },
    "docs": {
      "versionPersistence": "localStorage",
      "sidebar": {
        "hideable": false,
        "autoCollapseCategories": false
      }
    },
    "metadata": [],
    "prism": {
      "additionalLanguages": [],
      "theme": {
        "plain": {
          "color": "#bfc7d5",
          "backgroundColor": "#292d3e"
        },
        "styles": [
          {
            "types": [
              "comment"
            ],
            "style": {
              "color": "rgb(105, 112, 152)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "string",
              "inserted"
            ],
            "style": {
              "color": "rgb(195, 232, 141)"
            }
          },
          {
            "types": [
              "number"
            ],
            "style": {
              "color": "rgb(247, 140, 108)"
            }
          },
          {
            "types": [
              "builtin",
              "char",
              "constant",
              "function"
            ],
            "style": {
              "color": "rgb(130, 170, 255)"
            }
          },
          {
            "types": [
              "punctuation",
              "selector"
            ],
            "style": {
              "color": "rgb(199, 146, 234)"
            }
          },
          {
            "types": [
              "variable"
            ],
            "style": {
              "color": "rgb(191, 199, 213)"
            }
          },
          {
            "types": [
              "class-name",
              "attr-name"
            ],
            "style": {
              "color": "rgb(255, 203, 107)"
            }
          },
          {
            "types": [
              "tag",
              "deleted"
            ],
            "style": {
              "color": "rgb(255, 85, 114)"
            }
          },
          {
            "types": [
              "operator"
            ],
            "style": {
              "color": "rgb(137, 221, 255)"
            }
          },
          {
            "types": [
              "boolean"
            ],
            "style": {
              "color": "rgb(255, 88, 116)"
            }
          },
          {
            "types": [
              "keyword"
            ],
            "style": {
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "doctype"
            ],
            "style": {
              "color": "rgb(199, 146, 234)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "namespace"
            ],
            "style": {
              "color": "rgb(178, 204, 214)"
            }
          },
          {
            "types": [
              "url"
            ],
            "style": {
              "color": "rgb(221, 221, 221)"
            }
          }
        ]
      },
      "magicComments": [
        {
          "className": "theme-code-block-highlighted-line",
          "line": "highlight-next-line",
          "block": {
            "start": "highlight-start",
            "end": "highlight-end"
          }
        }
      ]
    },
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 3
    }
  },
  "baseUrlIssueBanner": true,
  "onDuplicateRoutes": "warn",
  "staticDirectories": [
    "static"
  ],
  "customFields": {},
  "plugins": [],
  "themes": [],
  "scripts": [],
  "headTags": [],
  "stylesheets": [],
  "clientModules": [],
  "titleDelimiter": "|",
  "noIndex": false,
  "markdown": {
    "mermaid": false
  }
};
